FROM ghcr.io/u-na-gi/rust-node-deno-wasm-pack:latest

RUN apt update && apt install -y libblas-dev libopenblas-dev libssl-dev pkg-config build-essential librocksdb-dev && \
apt autoremove -y && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

WORKDIR /app