FROM rust:1.72.1-slim-bullseye

RUN apt update -y && apt upgrade -y && apt install -y \
    build-essential \
    curl \
    git \
    libssl-dev \
    pkg-config \
    && rm -rf /var/lib/apt/lists/*

ENV CARGO_BUILD_TARGET_DIR=/tmp/target

RUN USER=root cargo new --bin repo
WORKDIR /repo
COPY ./Cargo.toml Cargo.toml

# RUN cargo build --release --color never && \
# rm src/*.rs && \
# rustup component add rustfmt

RUN rustup component add rustfmt

